# See http://goreleaser.com about this file
before:
  hooks:
    - go mod download
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archives:
- format: binary
  replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- tap:
    owner: progrhyme
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  homepage: https://go-shelp.netlify.app/
  description: Git-based package manager for shell scripts written in Go
  install:
    bin.install '{{ .Binary }}' => 'shelp'
  test: |
    system "#{bin}/shelp", '--version'
